const Types = {
  FETCH_BOOKS_REQUEST: 'FETCH_BOOKS_REQUEST',
  FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
  FETCH_BOOKS_RESPONSE: 'FETCH_BOOKS_RESPONSE',

  FETCH_BOOK_DETAIL_REQUEST: 'FETCH_BOOK_DETAIL_REQUEST',
  FETCH_BOOK_DETAIL_RESPONSE: 'FETCH_BOOK_DETAIL_RESPONSE',
  FETCH_BOOK_DETAIL_FAILURE: 'FETCH_BOOK_DETAIL_FAILURE',
};

export default Types;
